### ISSUE TITLE
Dual-sim phones

### ISSUE THREAD

**Issue by TaslimOseni** [emmanuelkehinde/quicksms-android#1]
In dual-sim phones, how does your library choose/manage the sim with which the SMS should be sent?

**Comment by TaslimOseni** [comment]
...or is this an update you're reserving for the future?

**Comment by emmanuelkehinde** [comment]
Hi Taslim,

You specify the phone numbers to receive the SMS before sending. Therefore, having multiple SIM cards does not affect the way the library or the APIs work.

**Comment by TaslimOseni** [comment]
I understand now.. I sorta misinterpreted the whole thing. Great work!!
